server:
  port: 8080
  
spring:
 data:
  elasticsearch:
   # 集群名
   #cluster-name: syncwt-es
   # 连接节点,注意在集群中通信都是9300端口，否则会报错无法连接上！
   cluster-nodes: 127.0.0.1:9300
   # 是否本地连接
   local: true
   repositories:
    # 仓库中数据存储
    enabled: true